models/Post.php
<?php

namespace app\models;

use general\ext\Helper;
use Imagine\Image\ManipulatorInterface;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\imagine\Image;

/**
 * This is the model class for table "post".
 *
 * @property integer $id
 * @property string $nick
 * @property string $title
 * @property string $keywords
 * @property string $description
 * @property string $text
 * @property integer $status
 * @property boolean $picture
 * @property boolean $pic_in_post
 * @property integer $site_id
 * @property integer $publish_at
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $author_id
 *
 * @property User $author
 * @property Site $site
 * @property TagPost[] $tagPosts
 * @property Tag[] $tags
 * @property array $marks
 * @property \yii\web\UploadedFile $image
 */
class Post extends ActiveRecord {
	const STATUS_DRAFT = 0;
	const STATUS_PUBLISHED = 1;
	const STATUS_WAITING = 2;

	public static $statuses = [
		self::STATUS_DRAFT => 'Черновик',
		self::STATUS_PUBLISHED => 'Опубликовано',
		self::STATUS_WAITING => 'Ожидает',
	];

	public $image;
	public $image_is_uploaded = false;

	private $_marks;

	public function behaviors() {
		return [
			TimestampBehavior::className(),
		];
	}
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'text'], 'required'],
			['marks', 'required', 'when' => function($model) {
				return (bool)$model->status;
			}, 'whenClient' => 'function (attribute, value) {
		        return $("#post-status").val() == "' . Post::STATUS_PUBLISHED . '";
		    }'],
			['title', 'trim'],
			['text', 'string'],
	        ['nick', 'filter', 'filter' => function ($value) {
		        if(!$value) {
			        return Helper::translit($this->title);
		        }
		        return $value;
	        }],
			[['status', 'picture', 'pic_in_post'], 'boolean'],
	        ['publish_at', 'filter', 'filter' => function($value) {
		        $parsed = strtotime($value);
		        if(!$parsed) {
			        return time();
		        }
		        return $parsed;
	        }],
			[['nick', 'title'], 'string', 'max' => 100],
	        ['keywords', 'filter', 'filter' => function($value) {
		        if(!$value) {
			        return Helper::cutter($this->marks, 128);
		        }
		        return $value;
	        }],
			['keywords', 'string', 'max' => 128],
	        ['description', 'filter', 'filter' => function($value) {
		        if(!$value) {
			        return Helper::cutter($this->text, 250);
		        }
		        return $value;
	        }],
			['description', 'string', 'max' => 250],
	        [
		        'image',
		        'file',
		        'skipOnEmpty' => false,
		        'when' => function($model) {
			        /* @var $model Post */
			        return (bool)$model->picture && !$model->image_is_uploaded;
		        },
		        'whenClient' => 'function (attribute, value) {
			        return $("#post-picture").prop("checked") && ' . (!$this->image_is_uploaded ? 'true' : 'false') . ';
			    }',
		        'uploadRequired' => 'Необходимо прикрепить картинку.',
	        ],
	        [
		        'image',
		        'file',
		        'extensions' => 'jpg, jpeg, gif',
		        'mimeTypes' => 'image/jpeg, image/gif',
	        ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nick' => 'Мнемоника',
            'title' => 'Название',
            'keywords' => 'Ключевые слова',
            'description' => 'Описание',
            'text' => 'Текст',
            'status' => 'Статус',
            'picture' => 'Картинка',
            'pic_in_post' => 'Показывать картинку внутри статьи?',
            'publish_at' => 'Дата публикации',
            'author_id' => 'Автор',
	        'marks' => 'Метки',
	        'image' => 'Картинка',
        ];
    }

	public function beforeSave($insert) {
		if(parent::beforeSave($insert)) {
			if ($this->isNewRecord) {
				$this->author_id = Yii::$app->user->id;
				$this->site_id = Yii::$app->controller->site->id;
			}
			return true;
		}
		return false;
	}

	public function afterFind() {
		parent::afterFind();
		if($this->picture) {
			$this->image_is_uploaded = true;
		}
	}

	public function getMarks() {
		if($this->_marks) {
			return $this->_marks;
		}
		if(!$this->isNewRecord) {
			$tags = [];
			foreach ($this->tags as $tag) {
				$tags[] = $tag->name;
			}
			return $this->_marks = implode(', ', $tags);
		}
		return '';
	}

	public function setMarks($val) {
		$this->_marks = $val;
	}

	public function saveImage() {
		if($this->image) {
			if($this->image_is_uploaded) {
				if(file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '.jpg')) {
					unlink(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '.jpg');
				}
				if(file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-big.jpg')) {
					unlink(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-big.jpg');
				}
				if(file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-small.jpg')) {
					unlink(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-small.jpg');
				}
			}

			if(!file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id)) {
				mkdir(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id, 0750, true);
			}

			$this->image->saveAs(\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '.jpg');
			//формируем большую картинку
			Image::thumbnail(
				\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '.jpg',
				640,
				640
			)->save(
				\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-big.jpg',
				['quality' => 90]
			);
			//формируем маленькую картинку
			Image::thumbnail(
				\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-big.jpg',
				320,
				320
			)->save(
				\Yii::getAlias('@app/web/i/post') . '/' . $this->site_id . '/' . $this->id . '-small.jpg',
				['quality' => 70]
			);
		}
	}

	public static function getImageLinks($model, $types = ['source', 'big', 'small']) {
		$ret = [];
		foreach ((array)$types as $type) {
			$ret[$type] = '//' . Yii::$app->request->serverName . '/i/post/' . $model['site_id'] . '/' . $model['id'];
			if($type == 'source') {
				$ret[$type] .= '.jpg';
			} else {
				$ret[$type] .= '-' . $type . '.jpg';
			}
		}
		return $ret;
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSite()
    {
        return $this->hasOne(Site::className(), ['id' => 'site_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagPosts()
    {
        return $this->hasMany(TagPost::className(), ['post_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->viaTable('tag_post', ['post_id' => 'id']);
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use app\models\Post;
use app\models\search\PostSearch;
use app\models\Tag;
use app\models\TagPost;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class PostController extends Controller {
	public $defaultAction = 'list';
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['create', 'delete', 'update', 'admin'],
				'rules' => [
					[
						'actions' => ['create', 'delete', 'update', 'admin'],
						'allow' => true,
						'matchCallback' => function ($rule, $action) {
							/* @var Controller $controller */
							$controller = \Yii::$app->controller;
							return $controller->isAdmin();
						}
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}
	private function createTags($tags, $model) {
		foreach ($tags as $mark) {
			$mark = trim($mark);
			if($tag = Tag::findOne(['name' => $mark])) {
				/* @var $tag Tag */
				$tag->frequency++;
				$tag->save();
			} else {
				$tag = new Tag();
				$tag->loadDefaultValues();
				$tag->name = $mark;
				$tag->site_id = $model->site_id;
				$tag->save();
			}

			$tag_post = new TagPost();
			$tag_post->post_id = $model->id;
			$tag_post->tag_id = $tag->id;
			$tag_post->save();
		}
	}
	private function deleteTags($tags, $model) {
		foreach ($tags as $mark) {
			$mark = trim($mark);
			if ($tag = Tag::findOne(['name' => $mark, 'site_id' => $this->site->id])) {
				/* @var $tag Tag */
				if ($tag->frequency == 1) {
					$tag->delete();
				} else {
					$tag->frequency--;
					$tag->save();
					if($tag_post = TagPost::findOne(['post_id' => $model->id, 'tag_id' => $tag->id])) {
						/* @var $tag_post TagPost */
						$tag_post->delete();
					}
				}
			}
		}
	}
	public function actionCreate() {
		$model = new Post();
		$model->loadDefaultValues();

		if (\Yii::$app->request->isPost) {
			$model->image = UploadedFile::getInstance($model, 'image');
			if($model->load(\Yii::$app->request->post()) && $model->save()) {
				$model->saveImage();
				//сохраняем метки
				$this->createTags(explode(',', $model->marks), $model);

				return $this->redirect(['update', 'id' => $model->id]);
			}
		}
		return $this->render('create', [
			'model' => $model,
		]);
	}
	public function actionUpdate($id)
	{
		/* @var Post $model */
		$model = Post::find()
			->where(['id' => $id])
			->andWhere(['site_id' => $this->site->id])
			->with('tags')
			->one();

		if (!$model) {
			throw new NotFoundHttpException();
		}

		if (\Yii::$app->request->isPost) {
			$oldMarks = [];
			foreach($model->tags as $val) {
				$oldMarks[] = $val->name;
			}

			$model->load(\Yii::$app->request->post());
			$model->image = UploadedFile::getInstance($model, 'image');
			if($model->save()) {
				$model->saveImage();

				$newMarks = [];
				foreach(explode(',', $model->marks) as $val) {
					$newMarks[] = trim($val);
				}

				$diffDelete = array_diff($oldMarks, $newMarks);
				$diffCreate = array_diff($newMarks, $oldMarks);

				$this->createTags($diffCreate, $model);
				$this->deleteTags($diffDelete, $model);

				return $this->redirect(['update', 'id' => $model->id]);
			}
		}
		return $this->render('update', [
			'model' => $model,
		]);
	}
	public function actionDelete($id) {
		/* @var Post $post */
		$post = Post::find()
			->where(['id' => $id])
			->andWhere(['site_id' => $this->site->id])
			->with('tags')
			->one();
		$model = clone $post;
		if($post->delete()) {
			if ($model->image_is_uploaded
				&& file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $model->site_id . '/' . $model->id . '.jpg')
			) {
				unlink(\Yii::getAlias('@app/web/i/post') . '/' . $model->site_id . '/' . $model->id . '.jpg');
			}
			$this->deleteTags(explode(',', $model->marks), $model);
		}
		return $this->redirect(['admin']);
	}
    public function actionList() {
	    $query = Post::find()
		    ->select(['post.id', 'post.title', 'post.description', 'post.picture', 'post.publish_at'])
		    ->where(['status' => Post::STATUS_PUBLISHED])
		    ->andWhere(['<', 'publish_at', time()])
		    ->andWhere(['post.site_id' => $this->site->id])
		    ->with('tags')
	        ->orderBy(['publish_at' => SORT_DESC]);

	    if(\Yii::$app->request->get('tag')) {
		    $query
			    ->joinWith('tags')
			    ->andWhere(['tag.name' => \Yii::$app->request->get('tag')]);
	    }

	    $dataProvider = new ActiveDataProvider([
		    'query' => $query,
		    'pagination' => [
			    'pageSize' => 15,
		    ],
	    ]);

        return $this->render('list', [
	        'dataProvider' => $dataProvider,
	        'tag' => \Yii::$app->request->get('tag'),
        ]);
    }
	public function actionAdmin() {
		$searchModel = new PostSearch();
		$dataProvider = $searchModel->search(\Yii::$app->request->get(), $this->site->id);

		return $this->render('admin', [
			'dataProvider' => $dataProvider,
			'searchModel' => $searchModel,
		]);
	}
    public function actionView($id) {
	    $model = Post::find()
	        ->where(['id' => $id])
		    ->andWhere(['status' => Post::STATUS_PUBLISHED])
		    ->andWhere(['<', 'publish_at', time()])
		    ->andWhere(['site_id' => $this->site->id])
		    ->with('tags')
	        ->one();
	    if(!$model) {
		    throw new NotFoundHttpException();
	    }
        return $this->render('view', [
	        'model' => $model,
        ]);
    }
}

views/post/_form.php
<?php

use app\models\Post;
use janisto\timepicker\TimePicker;
use vova07\imperavi\Widget;
use yii\helpers\Html;
use yii\jui\DatePicker;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="form">
    <?php $form = ActiveForm::begin([
	    'id' => 'post-form',
	    'options' => [
		    'enctype'=>'multipart/form-data',
	    ],
	    'fieldConfig' => [
		    'template' => '<div class="row">{label}{input}{error}</div>',
	    ],
	    'enableClientValidation' => true,
    ]); ?>

	<?= $form->errorSummary($model) ?>

    <?= $form->field($model, 'nick')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 100]) ?>

    <?= $form->field($model, 'keywords')->textarea(['rows' => 2, 'maxlength' => 128]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6, 'maxlength' => 250]) ?>

	<? echo $form->field($model, 'text')->widget(Widget::className(), [
		'settings' => [
			'lang' => 'ru',
			'minHeight' => 200,
			'plugins' => [
				'clips',
				'fullscreen'
			]
		]
	]); ?>

	<?= $form->field($model, 'marks')->textarea(['rows' => 2]) ?>

    <?= $form->field($model, 'status')->dropDownList([
	    Post::STATUS_PUBLISHED => Post::$statuses[ Post::STATUS_PUBLISHED ],
	    Post::STATUS_DRAFT => Post::$statuses[ Post::STATUS_DRAFT ],
    ]) ?>

	<?= TimePicker::widget([
		//'model' => $model,
		'value' => date(Yii::$app->params['dateFormat'], $model->publish_at),
		'attribute' => $model::className() . '[publish_at]',
		'language' => 'ru',
		'mode' => 'datetime',
		'clientOptions'=>[
			'dateFormat' => 'dd.mm.yy',
			'timeFormat' => 'HH:mm',
		]
	]) ?>

	<?= $form->field($model, 'picture', [
		'template' => '<div class="row checkbox">{label}{input}{error}</div>',
	])->checkbox([], false) ?>

	<? if($model->image_is_uploaded) { ?>
		<?= Html::beginTag('div', ['class' => 'row']) ?>
			<?= Html::img('//' . Yii::$app->request->serverName . '/i/post/' . $model->site_id . '/' . $model->id . '-small.jpg') ?>
		<?= Html::endTag('div') ?>
	<? } ?>

	<?= $form->field($model, 'image', [
		'template' => '<div class="row">{input}{error}</div>',
		'options' => [
			'style' => 'display: none;',
		],
	])->fileInput() ?>
	<?
	$this->registerJs('(function($) {
		function picture() {
			if($("#post-picture").prop("checked")) {
				$(".field-post-image").show();
			} else {
				$(".field-post-image").hide();
			}
		}
		$("#post-picture").click(function() {
			picture();
		});
		picture();
	})(jQuery)');
	?>

	<?= $form->field($model, 'pic_in_post', [
		'template' => '<div class="row checkbox">{label}{input}{error}</div>',
		'options' => [
			'checked' => $model->isNewRecord ? 'checked' : null
		],
	])->checkbox([], false) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Изменить') ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_view.php
<?php
/**
 * Project: Blog Platform - Seven Lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
/* @var $model app\models\Post */
use yii\helpers\Html;

?>
<div class="post">
	<?= Html::a($model->title, ['post/view', 'id'=>$model->id], ['class'=>'h1']); ?>
	<? if($model->picture) {
		echo Html::a(
			Html::img(
				Yii::$app->params['contentServer'] . '/images/' . $model->id.'-min.jpg',
				[
					'align'=>'left',
					'width'=>200,
					'alt' => $model->description,
				]
			),
			['post/view', 'id'=>$model->id]
		);
	}?>
	<?= $model->description ?>
	<br clear="both">
	<section class="meta">
		<? //@todo тег time ?>
		<p><?= date(Yii::$app->params['dateFormat'], $model->publish_at) ?> | Теги:
			<? $listTags = [];
			/* @var $tag app\models\Tag */
			foreach ($model->tags as $tag) {
				$listTags[]= Html::a($tag->name, ['post/list', 'tag' => $tag->name]);
			}
			echo implode(', ', $listTags); ?>
		</p>
	</section>
</div>

views/post/admin.php
<?php
/**
 * Project: Blog Platform - Seven Lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
use app\models\Post;
use general\assets\AdminAsset;
use yii\grid\ActionColumn;

/* @var $this yii\web\View */
AdminAsset::register($this);

$this->title = 'Управление записями';
$this->params['breadcrumbs'][] = $this->title;

/* @var yii\data\ActiveDataProvider $dataProvider */
/* @var app\models\search\PostSearch $searchModel */
echo \yii\grid\GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'layout' => '{items}{pager}',
	'columns' => [
		[
			'attribute' => 'id',
			'filterInputOptions' => ['style' => 'width: 50px;'],
		],
		'title',
		[
			'attribute' => 'status',
			'value' => function($data) {
				/* @var Post $data */
				if($data->status == Post::STATUS_PUBLISHED
				&& $data->publish_at > time()) {
					return Post::$statuses[ Post::STATUS_WAITING ];
				}
				return Post::$statuses[ $data->status ];
			},
			'filter' => Post::$statuses,
		],
		[
			'attribute' => 'publish_at',
			'format' => ['date', 'php:' . Yii::$app->params['dateFormat'] ],
		],
		[
			'class' => ActionColumn::className(),
			'template' => '{update} {delete}'
		],
	],
]);

views/post/create.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Создать пост';
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>
<div class="post-create">
    <h1><?= $this->title ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/post/list.php
<?php
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $tag string */
use yii\widgets\ListView;

if($tag) { ?>
	<h1>Записи с тегом <i><?= $tag ?></i></h1>
	<? $this->title = 'Записи с тегом ' . $tag;
} else { ?>
	<h1>Записи</h1>
<? }
$this->params['breadcrumbs'][] = 'Записи';

echo ListView::widget([
	'dataProvider' => $dataProvider,
	'itemView' => '_view',
	'layout' => '{items}{pager}',
]);

views/post/update.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = 'Изменить запись: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = 'Изменить запись';
?>
<div class="post-update">
    <h1><?= $this->title ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/post/view.php
<?php
use yii\helpers\Html;

/* @var $model app\models\Post */
/* @var $this yii\web\View */

$this->title = $model->title;
$this->params['breadcrumbs'][] = $this->title;

$this->registerMetaTag([
	'name' => 'description',
	'content' => $model->description,
], 'description');
$this->registerMetaTag([
	'name' => 'keywords',
	'content' => $model->keywords,
], 'keywords');

$this->registerJsFile('//yandex.st/highlightjs/7.3/highlight.min.js');
$this->registerCssFile('//yandex.st/highlightjs/7.3/styles/googlecode.min.css');
$this->registerJs('hljs.initHighlightingOnLoad();');
?>
<h1><?= $model->title ?></h1>

<div class="post">
	<? if($model->pic_in_post && $model->picture) {
		echo Html::img(
			Yii::$app->params['contentServer'] . '/images/' . $model->id.'.jpg',
			[
				'align' => 'right',
				'width' => 200,
				'alt' => $model->description,
			]
		);
	} ?>
	<?= $model->text ?>
	<br clear="both">
	<section class="meta">
		<? //@todo тег time ?>
		<p><?= date(Yii::$app->params['dateFormat'], $model->publish_at) ?> | Теги:
			<? $listTags = [];
			/* @var $tag app\models\Tag */
			foreach ($model->tags as $tag) {
				$listTags[]= Html::a($tag->name, ['post/list', 'tag' => $tag->name]);
			}
			echo implode(', ', $listTags); ?>
		</p>
	</section>
	<iframe src="http://comment.seven.loc/api/comment/create-frame" width="100%"></iframe>
</div>