controllers/MenuController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use Yii;
use app\models\Menu;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends Controller
{
    public function behaviors() {
        return [
	        'access' => [
		        'class' => AccessControl::className(),
		        'only' => ['create', 'delete', 'update', 'admin'],
		        'rules' => [
			        [
				        'actions' => ['create', 'delete', 'update', 'admin'],
				        'allow' => true,
				        'matchCallback' => function ($rule, $action) {
					        /* @var \app\extensions\Controller $controller */
					        $controller = \Yii::$app->controller;
					        return $controller->isAdmin();
				        }
			        ],
		        ],
	        ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Menu models.
     * @return mixed
     */
    public function actionAdmin() {
        $dataProvider = new ActiveDataProvider([
            'query' => Menu::find()->orderBy(['type' => SORT_ASC, 'number' => SORT_ASC]),
	        'pagination' => [
		        'pageSize' => 15,
	        ],
        ]);

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
        ]);
    }

	/**
	 * Creates a new Menu model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @throws Exception
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 * @return mixed
	 */
    public function actionCreate() {
        $model = new Menu();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
	        $transaction = Yii::$app->db->beginTransaction();
	        try {
		        //опускаем пункты, если необходимо
		        (new Query())
			        ->createCommand()
			        ->update(
				        Menu::tableName(),
				        [
					        'number' => new Expression('number + 1')
				        ],
				        [
					        'and',
					        ['>=', 'number', $model->number],
					        ['site_id' => $this->site->id, 'type' => $model->type],
				        ]
			        )
		            ->execute();
		        $model->save();
		        $transaction->commit();
	        } catch(Exception $e) {
		        $transaction->rollBack();
		        throw $e;
	        }

            return $this->redirect(['admin']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

	/**
	 * Updates an existing Menu model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id
	 * @throws Exception
	 * @throws NotFoundHttpException
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 * @return mixed
	 */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
	        $transaction = Yii::$app->db->beginTransaction();
	        try {
		        if($model->getOldAttribute('number') != $model->number) {
			        (new Query())
				        ->createCommand()
				        ->update(
					        'menu', [
						        'number' => new Expression('number - 1')
					        ],
					        [
						        'and',
						        ['>', 'number', $model->getOldAttribute('number')],
						        ['site_id' => $this->site->id, 'type' => $model->type],
					        ]
				        )
				        ->execute();
			        (new Query())
				        ->createCommand()
				        ->update(
					        'menu', [
						        'number' => new Expression('number + 1')
					        ],
					        [
						        'and',
						        ['>=', 'number', $model->number],
						        ['site_id' => $this->site->id, 'type' => $model->type],
					        ]
				        )
				        ->execute();
		        }
		        $model->save();
		        $transaction->commit();
	        } catch(Exception $e) {
		        $transaction->rollBack();
		        throw $e;
	        }
            return $this->redirect(['admin']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

	/**
	 * Deletes an existing Menu model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 * @param integer $id
	 * @throws Exception
	 * @throws NotFoundHttpException
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 * @return mixed
	 */
    public function actionDelete($id) {
        $model = $this->findModel($id);
	    $transaction = Yii::$app->db->beginTransaction();
	    try {
		    (new Query())
			    ->createCommand()
			    ->update(
				    'menu', [
					    'number' => new Expression('number - 1')
				    ],
				    [
					    'and',
					    ['>', 'number', $model->number],
					    ['site_id' => $this->site->id, 'type' => $model->type],
				    ]
			    )
			    ->execute();
		    $model->delete();
		    $transaction->commit();
	    } catch(Exception $e) {
		    $transaction->rollBack();
		    throw $e;
	    }
        return $this->redirect(['admin']);
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if ($model = Menu::findOne($id)) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\extensions\Controller;
use app\models\Post;
use app\models\search\PostSearch;
use app\models\Tag;
use app\models\TagPost;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

class PostController extends Controller {
	public $defaultAction = 'list';
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['create', 'delete', 'update', 'admin'],
				'rules' => [
					[
						'actions' => ['create', 'delete', 'update', 'admin'],
						'allow' => true,
						'matchCallback' => function ($rule, $action) {
							/* @var Controller $controller */
							$controller = \Yii::$app->controller;
							return $controller->isAdmin();
						}
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::className(),
				'actions' => [
					'delete' => ['post'],
				],
			],
		];
	}
	private function createTags($tags, $model) {
		foreach ($tags as $mark) {
			$mark = trim($mark);
			if($tag = Tag::findOne(['name' => $mark])) {
				/* @var $tag Tag */
				$tag->frequency++;
				$tag->save();
			} else {
				$tag = new Tag();
				$tag->loadDefaultValues();
				$tag->name = $mark;
				$tag->site_id = $model->site_id;
				$tag->save();
			}

			$tag_post = new TagPost();
			$tag_post->post_id = $model->id;
			$tag_post->tag_id = $tag->id;
			$tag_post->save();
		}
	}
	private function deleteTags($tags, $model) {
		foreach ($tags as $mark) {
			$mark = trim($mark);
			if ($tag = Tag::findOne(['name' => $mark, 'site_id' => $this->site->id])) {
				/* @var $tag Tag */
				if ($tag->frequency == 1) {
					$tag->delete();
				} else {
					$tag->frequency--;
					$tag->save();
					if($tag_post = TagPost::findOne(['post_id' => $model->id, 'tag_id' => $tag->id])) {
						/* @var $tag_post TagPost */
						$tag_post->delete();
					}
				}
			}
		}
	}
	public function actionCreate() {
		$model = new Post();
		$model->loadDefaultValues();

		if (\Yii::$app->request->isPost) {
			$model->image = UploadedFile::getInstance($model, 'image');
			if($model->load(\Yii::$app->request->post()) && $model->save()) {
				$model->saveImage();
				//сохраняем метки
				$this->createTags(explode(',', $model->marks), $model);

				return $this->redirect(['update', 'id' => $model->id]);
			}
		}
		return $this->render('create', [
			'model' => $model,
		]);
	}
	public function actionUpdate($id)
	{
		/* @var Post $model */
		$model = Post::find()
			->where(['id' => $id])
			->andWhere(['site_id' => $this->site->id])
			->with('tags')
			->one();

		if (!$model) {
			throw new NotFoundHttpException();
		}

		if (\Yii::$app->request->isPost) {
			$oldMarks = [];
			foreach($model->tags as $val) {
				$oldMarks[] = $val->name;
			}

			$model->load(\Yii::$app->request->post());
			$model->image = UploadedFile::getInstance($model, 'image');
			if($model->save()) {
				$model->saveImage();

				$newMarks = [];
				foreach(explode(',', $model->marks) as $val) {
					$newMarks[] = trim($val);
				}

				$diffDelete = array_diff($oldMarks, $newMarks);
				$diffCreate = array_diff($newMarks, $oldMarks);

				$this->createTags($diffCreate, $model);
				$this->deleteTags($diffDelete, $model);

				return $this->redirect(['update', 'id' => $model->id]);
			}
		}
		return $this->render('update', [
			'model' => $model,
		]);
	}
	public function actionDelete($id) {
		/* @var Post $post */
		$post = Post::find()
			->where(['id' => $id])
			->andWhere(['site_id' => $this->site->id])
			->with('tags')
			->one();
		$model = clone $post;
		if($post->delete()) {
			if ($model->image_is_uploaded
				&& file_exists(\Yii::getAlias('@app/web/i/post') . '/' . $model->site_id . '/' . $model->id . '.jpg')
			) {
				unlink(\Yii::getAlias('@app/web/i/post') . '/' . $model->site_id . '/' . $model->id . '.jpg');
			}
			$this->deleteTags(explode(',', $model->marks), $model);
		}
		return $this->redirect(['admin']);
	}
    public function actionList() {
	    $query = Post::find()
		    ->select(['post.id', 'post.title', 'post.description', 'post.picture', 'post.publish_at'])
		    ->where(['status' => Post::STATUS_PUBLISHED])
		    ->andWhere(['<', 'publish_at', time()])
		    ->andWhere(['post.site_id' => $this->site->id])
		    ->with('tags')
	        ->orderBy(['publish_at' => SORT_DESC]);

	    if(\Yii::$app->request->get('tag')) {
		    $query
			    ->joinWith('tags')
			    ->andWhere(['tag.name' => \Yii::$app->request->get('tag')]);
	    }

	    $dataProvider = new ActiveDataProvider([
		    'query' => $query,
		    'pagination' => [
			    'pageSize' => 15,
		    ],
	    ]);

        return $this->render('list', [
	        'dataProvider' => $dataProvider,
	        'tag' => \Yii::$app->request->get('tag'),
        ]);
    }
	public function actionAdmin() {
		$searchModel = new PostSearch();
		$dataProvider = $searchModel->search(\Yii::$app->request->get(), $this->site->id);

		return $this->render('admin', [
			'dataProvider' => $dataProvider,
			'searchModel' => $searchModel,
		]);
	}
    public function actionView($id) {
	    $model = Post::find()
	        ->where(['id' => $id])
		    ->andWhere(['status' => Post::STATUS_PUBLISHED])
		    ->andWhere(['<', 'publish_at', time()])
		    ->andWhere(['site_id' => $this->site->id])
		    ->with('tags')
	        ->one();
	    if(!$model) {
		    throw new NotFoundHttpException();
	    }
        return $this->render('view', [
	        'model' => $model,
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\filters\AccessControl;
use app\extensions\Controller;
use app\models\AuthKey;
use app\models\User;
use general\ext\api\auth\AuthApi;
use general\ext\api\auth\AuthUrlCreator;
use Yii;
use yii\web\Response;
use app\models\forms\SiteForm;

class SiteController extends Controller {
    public $defaultAction = 'index';
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function actionIndex() {
        return $this->render('index');
    }
	/*public function actionSignup() {
		$model = new SignupForm();
		if ($model->load(Yii::$app->request->post())) {
			if ($user = $model->signup()) {
				if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
					return $this->goHome();
				}
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}*/
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only' => ['update'],
				'rules' => [
					[
						'actions' => ['update'],
						'allow' => true,
						'matchCallback' => function ($rule, $action) {
							/* @var Controller $controller */
							$controller = \Yii::$app->controller;
							return $controller->isAdmin();
						}
					],
				],
			],
		];
	}
    public function actionLoginWithAuthKey($result) {
	    $this->layout = 'emptyHtml';
	    if($result == 'success') {
		    if (!Yii::$app->user->isGuest) {
			    return $this->render('redirect', ['url' => '/']);
		    }

		    $mark = Yii::$app->request->get('key');
		    if($key = AuthApi::userGetServiceAuthKey($mark)) {
			    $user = User::getFromAuth($key['user_id']);

			    $model = new AuthKey();
			    $model->auth_key = $key['auth_key'];
			    $model->browser = Yii::$app->request->userAgent;
			    $model->ip = Yii::$app->request->userIP;
			    $model->user_id = $key['user_id'];
			    $model->save();

			    if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				    return $this->render('refresh');
			    }
		    } else {
			    //@todo сделать вывод ошибки
		    }
	    }
	    return $this->render('redirect', ['url' => '/']);
    }
	public function actionLoginWithMark($mark) {
		if (!Yii::$app->user->isGuest) {
			return '';
		}

		\Yii::$app->response->format = Response::FORMAT_JSONP;
		if($key = AuthApi::userGetServiceAuthKey($mark)) {
			$user = User::getFromAuth($key['user_id']);

			$model = new AuthKey();
			$model->auth_key = $key['auth_key'];
			$model->browser = Yii::$app->request->userAgent;
			$model->ip = Yii::$app->request->userIP;
			$model->user_id = $key['user_id'];
			$model->save();

			if (Yii::$app->user->login($user, Yii::$app->params['durationAuth'])) {
				return [
					'data' => 'success',
					'callback' => 'loginWithMark',
				];
			}
		}
		return [
			'data' => 'error',
			'callback' => 'loginWithMark',
		];
	}
	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		return $this->render('login');
	}
    public function actionLogout() {
        User::logout();
	    return $this->redirect(
		    AuthUrlCreator::userLogout(
			    Yii::$app->id,
			    '//' . Yii::$app->request->getServerName()));
    }
	public function actionLogoutEverywhere() {
		User::logoutEverywhere();
		return $this->redirect(
			AuthUrlCreator::userLogoutEverywhere(
				Yii::$app->id,
				'//' . Yii::$app->request->getServerName()));
	}
	public function actionUpdate()
	{
		/* @var $model SiteForm */
		$model = SiteForm::findOne($this->site->id);

		if (Yii::$app->request->isPost) {
			$model->load(Yii::$app->request->post());
			$model->save();
		}

		return $this->render('update', [
			'model' => $model,
		]);

	}
}

views/layouts/empty.php
<?php
/**
 * Project: Auth - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
/* @var $content string */
echo $content;

views/layouts/emptyHtml.php
<?php
/**
 * Project: Auth - Seven lights
 * User: Evgeny Rusanov
 * E-mail: admin@dudev.ru
 * Site: dudev.ru
 */
use yii\helpers\Html;
/* @var $this \yii\web\View */
/* @var $content string */
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>"/>
	<?= Html::csrfMetaTags() ?>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
	<?= !empty($this->params['head']) ? $this->params['head'] : '' ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use app\models\Menu;
use general\widgets\MonoMenu;
use yii\helpers\Html;
use app\assets\AppAsset;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

/* @var $controller app\extensions\Controller */
$controller = Yii::$app->controller;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="google-site-verification" content="zQMN8ZleT4eOxtLqnjrHQekcmIvjCJKWjm1eWKhtagE" />
    <?= Html::csrfMetaTags() ?>
    <title><?= $this->title ? Html::encode($this->title) . ' - ' : '' ?><?= $controller->site->name ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<header>
	<a href="/" title="Главная - <?= $controller->site->name ?>"><?= $controller->site->name ?></a>
</header>
<div id="page">
	<?= Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
		'homeLink'=>[
			'label' => 'Главная',
			'url' => Yii::$app->homeUrl,
		],
		'itemTemplate' => '<li>{link} » </li>',
	]) ?>
	<div id="content">
		<?= $content ?>
	</div>
	<div id="sidebar">
		<nav>
			<h4>Меню</h4>
			<?= MonoMenu::widget([
				'items' => Menu::find()->where(['type' => Menu::TYPE_MENU])->all(),
			]) ?>
			<? /* @todo ['label' => 'Обо мне', 'url' => '/about-me.html'],
			@todo ['label' => 'Услуги', 'url' => '/offers.html'],
			@todo ['label' => 'Контакты', 'url' => '/contacts.html'], */ ?>
		</nav>
		<nav>
			<h4>Категории</h4>
			<?= MonoMenu::widget([
				'items' => Menu::find()->where(['type' => Menu::TYPE_CATEGORY])->all(),
			]) ?>
		</nav>
		<?php
		/* @var \app\extensions\Controller $controller */
		$controller = Yii::$app->controller;
		if(!Yii::$app->user->isGuest && $controller->isAdmin()) {
			if(Yii::$app->requestedRoute == 'post/view') {
				echo Html::beginTag('nav');
				echo Html::tag('h4', 'Управление записью');
				echo \yii\widgets\Menu::widget([
					'items' => [
						['label' => 'Изменить', 'url' => ['post/update', 'id' => Yii::$app->request->get('id')]],
					]
				]);
				echo Html::endTag('nav');
			}
			echo Html::beginTag('nav');
			echo Html::tag('h4', 'Управление');
			echo \yii\widgets\Menu::widget([
				'items' => [
					['label' => 'Создать запись', 'url' => ['post/create']],
					['label' => 'Записи', 'url' => ['post/admin']],
					//['label' => 'Комментарии', 'url' => ['comment/index']],
					['label' => 'Меню', 'url' => ['menu/admin']],
					['label' => 'Страницы', 'url' => ['page/index']],
					['label' => 'Редакторы', 'url' => ['redactor/index']],
					['label' => 'Настройки сайта', 'url' => ['site/update']],
					['label' => 'Выход', 'url' => ['site/logout']],
				]
			]);
			echo Html::endTag('nav');
		} ?>

		<?php
		/*<h4>Поиск</h4>
		<form action="#" class="s">
			<input id="search" type="text" value="Я ищу...">
		</form>*/
		?>

		<?php //$this->widget('TagCloud'); ?>

</div>
<footer>
	<p>&copy;&nbsp;2008 -  <?= date('Y') ?>&nbsp;Евгений Русанов</p>
</footer>
</div>
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter21505294 = new Ya.Metrika({id:21505294, webvisor:true, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/21505294" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>